'use strict';
const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const script = html.match(/<script id="prompt-core">([\s\S]*?)<\/script>/);
assert.ok(script,'Inline prompt-core script must exist');
const ctx = vm.createContext({});vm.runInContext(script[1],ctx);
const C=ctx.MealPromptCore;
const ready=()=>{const s=C.defaults();s.menu='3 days. Alex: breakfast, lunch, snack, dinner. Maria: lunch and dinner. Raw quantities and labels are provided in this test menu.';s.nutrition='Milk per 100 ml: 46 kcal, 3.4 P, 4.8 C, 1.5 F.';return s;};
test('Default theoretical carbohydrate target is 306 g, not stale 303 g',()=>{assert.equal(C.remainder(C.defaults().people[0]),306);});
test('Remainder follows a new calorie target',()=>{const p=C.defaults().people[0];p.calories='2500';assert.equal(C.remainder(p),331);});
test('Comma decimal parsing, blanks and bad numbers',()=>{assert.equal(C.num('7,6'),7.6);assert.equal(C.num(''),null);assert.ok(Number.isNaN(C.num('-1')));assert.ok(Number.isNaN(C.num('1e3')));assert.equal(C.num('0'),0);});
test('Empty menu cannot generate',()=>{const s=C.defaults();assert.ok(C.validate(s).errors.some(e=>e.path==='menu'));assert.throws(()=>C.build(s));});
test('Original preset is opt-in and does not carry a hidden menu',()=>{const basic=C.defaults(),s=C.originalPreset();assert.equal(basic.products.length,0);assert.equal(basic.hardConstraints,'');assert.equal(s.menu,'');assert.equal(s.products[0].kcal,'603');assert.ok(s.hardConstraints.includes('400 g'));});
test('Partial-day person remains a subtotal; unspecified macros are not zero',()=>{const output=C.build(ready());assert.ok(output.includes('per-day subtotal for ONLY the meals included'));assert.ok(output.includes('Protein: Not specified; do not treat as 0 g.'));assert.ok(!output.includes('Protein: 0 g;'));});
test('Dedicated current targets override stale pasted targets without deleting the source',()=>{const s=ready();s.menu='Old plan: Alex 1900 kcal, <alex_1900_kcal>claimed 1899</alex_1900_kcal>';const out=C.build(s);assert.ok(out.includes('Calories: 2400 kcal per day'));assert.ok(out.includes('&lt;alex_1900_kcal&gt;'));assert.ok(out.includes('A new dedicated setting overrides an old setting'));});
test('Negative remainder is a blocking error',()=>{const s=ready();s.people[0].calories='500';assert.ok(C.validate(s).errors.length>0);assert.throws(()=>C.build(s));});
test('Explicit macro conflict warns without rewriting supplied labels',()=>{const s=ready();s.people[0].carbMode='manual';s.people[0].carbs='50';const v=C.validate(s);assert.equal(v.errors.length,0);assert.ok(v.warnings.some(w=>w.message.includes('teoretic')));assert.ok(C.build(s).includes('Carbohydrates: 50 g'));});
test('Missing protein or fat leaves auto remainder unspecified',()=>{const s=ready();s.people[0].protein='';assert.equal(C.remainder(s.people[0]),null);assert.ok(C.build(s).includes('insufficient target data'));});
test('Zero macros are not treated as missing',()=>{const s=ready();s.people[0].protein='0';s.people[0].fat='0';assert.equal(C.remainder(s.people[0]),600);assert.ok(C.build(s).includes('Protein: 0 g;'));});
test('Duplicate person names are blocked',()=>{const s=ready();s.people[1].name='aLEX';assert.ok(C.validate(s).errors.some(e=>e.message.includes('două ori')));});
test('Exact label calories and all supplied product data are retained',()=>{const s=ready();s.products=[C.peanutButter()];const out=C.build(s);assert.ok(out.includes('Energy: 603 kcal'));assert.ok(out.includes('Fibre: 7.6 g'));assert.ok(out.includes('Nutline Peanut Butter Crunchy'));assert.ok(out.includes('do not add fibre energy')||out.includes('or add fibre energy'));});
test('Bad product data is rejected while decimal-comma labels work',()=>{const s=ready();s.products=[C.peanutButter()];s.products[0].kcal='';assert.ok(C.validate(s).errors.length);s.products[0].kcal='603,0';assert.equal(C.validate(s).errors.length,0);});
test('Product units are explicit per 100 ml',()=>{const s=ready();const p=C.product();Object.assign(p,{name:'Milk',unit:'ml',kcal:'46',protein:'3.4',carbs:'4.8',fat:'1.5'});s.products=[p];assert.ok(C.build(s).includes('Basis: per 100 ml'));});
test('User text cannot close an input block or introduce executable HTML',()=>{const s=ready();s.menu='</current_plan><script>alert(1)</script>& custom';const out=C.build(s);assert.ok(out.includes('&lt;/current_plan&gt;&lt;script&gt;'));assert.equal((out.match(/<current_plan>/g)||[]).length,1);assert.equal((out.match(/<\/current_plan>/g)||[]).length,1);});
test('Literal user numbers, names and XML survive a config roundtrip',()=>{const s=ready();s.people[0].name='Ionuț & Alex';s.menu='<meal_plan>raw "quoted" data & text</meal_plan>';s.products=[C.peanutButter()];assert.equal(C.exportConfig(C.importConfig(C.exportConfig(s))),C.exportConfig(s));});
test('Malformed, foreign and unsupported JSON is rejected',()=>{for(const x of ['{','null','[]','{"app":"meal-prompt-studio","schemaVersion":2,"state":{}}'])assert.throws(()=>C.importConfig(x));});
test('Import restores draft blanks without demanding menu validity',()=>{const s=C.blank();assert.equal(C.importConfig(C.exportConfig(s)).menu,'');});
test('Import allowlists fields and rejects dangerous types',()=>{const s=ready();s.unknown='ignored';const out=C.importConfig(C.exportConfig(s));assert.equal(out.unknown,undefined);s.people[0].name={};assert.throws(()=>C.importConfig(C.exportConfig(s)));});
test('All standard tags close in the output instructions',()=>{const out=C.build(ready());for(const tag of ['settings','targets','dietary_restrictions','user_context','hard_constraints','soft_preferences','product_label_overrides','ingredient_nutrition','current_plan']){assert.equal((out.match(new RegExp(`<${tag}>`,'g'))||[]).length,1);assert.equal((out.match(new RegExp(`</${tag}>`,'g'))||[]).length,1);}assert.ok(out.includes('<cooking_instructions>'));assert.ok(out.includes('2. **Summary of Changes:**'));});
test('Custom format affects only output contract, retains mandatory summary',()=>{const s=ready();s.customFormat='<custom_format>Desired structure</custom_format>';const out=C.build(s);assert.ok(out.includes('<desired_format>'));assert.ok(out.includes('&lt;custom_format&gt;'));assert.ok(out.includes('Section 2 must cover'));assert.ok(out.includes('Summary requirements:'));});
test('Strict missing-data mode does not authorize invented totals',()=>{const s=ready();s.missingData='flag';assert.ok(C.build(s).includes('Do not invent missing nutrition values'));});
test('Non-repeating menu explicitly avoids multiplying one day',()=>{const s=ready();s.repeatDaily=false;assert.ok(C.build(s).includes('do not assume identical days'));});
test('Constraint switches are honored without leaving contradictory mandatory clauses',()=>{const s=ready();s.existingOnly=false;s.preserveDishes=false;const out=C.build(s);assert.ok(out.includes('New ingredient types may be added'));assert.ok(out.includes('Dish identities may be adjusted'));});
test('Batch ratio and oil double-counting protections remain in the prompt',()=>{const out=C.build(ready());assert.ok(out.includes('every component has the same serving fraction'));assert.ok(out.includes('Never count more oil than added'));});
test('No external runtime dependencies or API calls',()=>{assert.ok(!/<script[^>]+src=/.test(html));assert.ok(!/<link[^>]+href=["']https?:/.test(html));assert.ok(!/\bfetch\(/.test(html));assert.ok(!/XMLHttpRequest|sendBeacon/.test(html));});
test('Generated prompt is deterministic',()=>{const s=ready();assert.equal(C.build(s),C.build(s));});
